import type { PowerliftingRecord } from '../types/records';

/**
 * British Powerlifting Records Database
 *
 * This file is auto-generated by scripts/build-records.js
 * DO NOT EDIT MANUALLY - Your changes will be overwritten
 *
 * To update records:
 * 1. Edit JSON files in data-source/
 * 2. Run: npm run build:data
 *
 * Last generated: 2025-11-18T09:56:35.644Z
 */

export const records: PowerliftingRecord[] = [
    {
      region: "England",
      name: "John Smith",
      weightClass: "83kg",
      gender: "M",
      lift: "squat",
      ageCategory: "Open",
      record: 280.5,
      dateSet: "2024-01-15",
      equipment: "unequipped"
    },
    {
      region: "London",
      name: "Michael Taylor",
      weightClass: "93kg",
      gender: "M",
      lift: "total",
      ageCategory: "Open",
      record: 725,
      dateSet: "2023-12-15",
      equipment: "equipped"
    },
    {
      region: "Northern Ireland",
      name: "Sarah Brown",
      weightClass: "59kg",
      gender: "F",
      lift: "squat",
      ageCategory: "Junior",
      record: 145,
      dateSet: "2024-03-05",
      equipment: "unequipped"
    },
    {
      region: "Scotland",
      name: "Emma Wilson",
      weightClass: "66kg",
      gender: "F",
      lift: "deadlift",
      ageCategory: "Open",
      record: 195,
      dateSet: "2023-11-20",
      equipment: "equipped"
    },
    {
      region: "Wales",
      name: "David Jones",
      weightClass: "105kg",
      gender: "M",
      lift: "bench_press",
      ageCategory: "M1",
      record: 185.5,
      dateSet: "2024-02-10",
      equipment: "unequipped"
    }
  ];
